### ISSUE TITLE
css_loader cannot resolve 'file' or 'directory'.

### ISSUE THREAD

**Issue by pavelbeliaev** [matthewlehner/phoenix-webpack-example#7]
Hi,
I followed your tutorial, and everything works fine except for '**css_loader**'. It can not deal with 'url'.
That's what I got:

`ERROR in ./~/css-loader!./~/sass-loader?includePaths[]=/home/pvb/projects/whatever/node_modules!./web/static/css/app.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/glyphicons-halflings-regular.eot in /home/pvb/projects/whatever/web/static/css
 @ ./~/css-loader!./~/sass-loader?includePaths[]=/home/pvb/projects/whatever/node_modules!./web/static/css/app.scss 6:4260-4312 6:4335-4387
`

I tried to add **url_loader** and **file_loader**,(https://github.com/webpack/css-loader/issues/38) but without success.
Then I checked your `css/app.scss` and not found any urls or fonts.
Did you delete them or move? What is going on?

Thank you.

**Comment by matthewlehner** [comment]
I've noticed the same problem and don't have a good solution for you – the problem is that the SCSS loader doesn't know where the specific font file is coming from, it could be local, in an npm package or relative to the production site itself.

The best explanation I've seen is this: https://github.com/jtangelder/sass-loader/issues/40

I hope this works for you!
